name = "selfbyt"

[build]
command = "./cloudflare-build.sh"
publish = ".next"

[vars]
NODE_VERSION = "20.0.0"

[env.preview]
[env.preview.vars]
NODE_ENV = "development"
NODE_VERSION = "20.0.0"

[env.production]
[env.production.vars]
NODE_ENV = "production"
NODE_VERSION = "20.0.0"
