# Cloudflare Pages configuration
name = "selfbyt"
pages_build_output_dir = ".next"

# Build command
build = { command = "./cloudflare-build.sh", cwd = ".", output_directory = ".next" }

# Environment variables
[vars]
NODE_VERSION = "20.0.0"

# For development environment
[env.development]
[env.development.vars]
NODE_ENV = "development"

# For production environment
[env.production]
[env.production.vars]
NODE_ENV = "production"
