name = "selfbyt"

# This is required for Cloudflare Pages to recognize the configuration
pages_build_output_dir = ".next"

[build]
command = "./cloudflare-build.sh"

[vars]
NODE_VERSION = "20.0.0"

[env.preview]
[env.preview.vars]
NODE_ENV = "development"
NODE_VERSION = "20.0.0"

[env.production]
[env.production.vars]
NODE_ENV = "production"
NODE_VERSION = "20.0.0"
