# Cloudflare Pages configuration via wrangler.toml

# Required project name
name = "selfbyt-site"

# Build configuration
[build]
command = "./cloudflare-build.sh"
publish = ".cloudflare-output"

# Configure Pages
[site]
bucket = "."

# Environment variables
[env.production]
node_version = "20.0.0"
