# Cloudflare Pages configuration via wrangler.toml

# Build configuration
build_command = "./cloudflare-build.sh"
pages_build_output_dir = ".cloudflare-output"

# Environment variables
[vars]
NODE_VERSION = "20.0.0"
NPM_VERSION = "9.6.7"
